project:
  type: website

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sam0287/blog
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme: [cosmo, custom.scss]
    code-copy: true
    code-fold: true          # This makes them collapsed by default
    code-summary: "Show Code" # This is the text on the button
    include-in-header:
      text: |
        <style>
        .quarto-categories, 
        .quarto-title-meta-category, 
        .quarto-listing-category,
        .category { 
          display: none !important; 
        }
        </style>
        <script data-goatcounter="https://sam0287.goatcounter.com/count"
                async src="//gc.zgo.at/count.js"></script>
